---
framework: jest
postMerge: 
  pattern: 
    - "./test/**/options.spec.ts"
  strategy: 
    threshold: <5|100s|30m|6h>
    type: <commit|time>
preMerge:
  pattern:
    - "./test/**/options.spec.ts"
preRun:
     command:
        - npm i
postRun:
     command:
        - node --version
version: 2.0
